# Generated by Django 2.0.2 on 2018-02-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='whatever.png', upload_to=''),
            preserve_default=False,
        ),
    ]
